//! Replay the tracked fuzz corpus, and write the seeds the fuzzer starts from.
//!
//! A fuzzer finds an input once. This is what keeps it found: every input in
//! `tests/fuzz-corpus/` runs through the same body [`fuzz`][common::fuzz] hands
//! libFuzzer, on every `cargo test`, on every platform CI covers — including
//! the ones nobody fuzzes on. When the fuzzer produces a crash, minimise it
//! with `cargo +nightly fuzz tmin`, drop the result in the matching directory,
//! and it becomes a permanent test.
//!
//! What is committed is a bounded sample of the minimised corpus (`cargo
//! +nightly fuzz cmin`) rather than the whole of it: at most 24 files and 16 KB
//! a target, because `tests/` ships inside the published crate and a corpus is
//! the kind of thing that grows to megabytes if nothing stops it. Crash
//! witnesses are kept whatever their size; the rest is a sample, and the full
//! corpus is regenerated by running the fuzzer. This is a regression suite for
//! paths a fuzzer bothered to find, not an archive.

mod common;
use common::*;
use opus_pure::{Application, CafOpusWriter, OggOpusWriter, OpusHead, OpusTags};

/// One fuzz target's body, as the fuzz crate hands it to libFuzzer.
type Body = fn(&[u8]);

/// Every target, and the body that runs it.
const TARGETS: [(&str, Body); 4] = [
    ("decode_stream", common::fuzz::decode_stream),
    ("ogg_read", common::fuzz::ogg_read),
    ("caf_read", common::fuzz::caf_read),
    ("packet_shape", common::fuzz::packet_shape),
];

fn corpus_dir(target: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fuzz-corpus")
        .join(target)
}

/// Files in a corpus directory, sorted, so a failure names the same input on
/// every run and on every filesystem.
fn corpus_files(target: &str) -> Vec<std::path::PathBuf> {
    let dir = corpus_dir(target);
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return Vec::new();
    };
    let mut files: Vec<_> = entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_file())
        .collect();
    files.sort();
    files
}

#[test]
fn the_tracked_corpus_is_still_handled_safely() {
    let mut total = 0usize;
    for (target, body) in TARGETS {
        let files = corpus_files(target);
        assert!(
            !files.is_empty(),
            "no corpus for `{target}` in {}: the replay has become a no-op",
            corpus_dir(target).display()
        );
        for path in files {
            let data = std::fs::read(&path).expect("corpus file");
            // The panic message names the file, because a minimised corpus
            // entry is meaningless without knowing which one it was.
            let name = path.display().to_string();
            let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| body(&data)));
            assert!(outcome.is_ok(), "{target} panicked on {name}");
            total += 1;
        }
    }
    assert!(total > 0, "the corpus is empty");
}

/// Write valid streams for the fuzzer to start from.
///
/// Coverage-guided fuzzing from nothing spends its first hours rediscovering
/// the TOC byte. These seeds hand it working streams in each target's own input
/// format, so it starts at the bitstream and the container rather than at the
/// front door. Ignored by default because it writes into `fuzz/`, which is not
/// part of the published crate:
///
/// ```text
/// cargo test --test fuzz_corpus -- --ignored write_fuzz_seeds
/// cargo +nightly fuzz run decode_stream
/// ```
#[test]
#[ignore = "writes seed files into fuzz/corpus for `cargo +nightly fuzz run`"]
fn write_fuzz_seeds() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("fuzz/corpus");
    let mut written = 0usize;

    // (rate, channels, bitrate) chosen to span the three coding modes: SILK at
    // the bottom, hybrid in the middle, CELT at the top.
    let configs = [
        (8_000i32, 1usize, 12_000i32),
        (16_000, 1, 20_000),
        (48_000, 1, 24_000),
        (48_000, 2, 64_000),
        (48_000, 2, 160_000),
    ];

    for (i, &(rate, channels, bitrate)) in configs.iter().enumerate() {
        let mono = speech_like(rate, rate as usize / 2);
        let pcm = if channels == 2 {
            interleave(&[mono.clone(), music_like(rate, rate as usize / 2)])
        } else {
            mono
        };
        let mut codec = Codec::new(rate, channels, Application::Audio).bitrate(bitrate);
        let packets = codec.encode_all(&pcm);

        // `packet_shape` takes one raw packet.
        for (j, pkt) in packets.iter().take(4).enumerate() {
            written += write_seed(&root, "packet_shape", &format!("{i}-{j}"), pkt);
        }

        // `decode_stream` takes a configuration byte and then packets behind a
        // two-byte prefix, so the seed has to be assembled in that shape.
        let cfg = match rate {
            8_000 => 0u8,
            16_000 => 1,
            24_000 => 2,
            _ => 3,
        } | if channels == 2 { 0b100 } else { 0 };
        let mut stream = vec![cfg];
        for (j, pkt) in packets.iter().enumerate() {
            // Drop every seventh packet, so the seed also carries the
            // concealment path rather than only clean decoding.
            if j % 7 == 6 {
                stream.extend_from_slice(&[0, 0]);
            }
            let len = pkt.len().min(0x7fff);
            stream.push((len >> 8) as u8);
            stream.push(len as u8);
            stream.extend_from_slice(&pkt[..len]);
        }
        written += write_seed(&root, "decode_stream", &format!("{i}"), &stream);

        // `ogg_read` takes a whole container.
        let head = OpusHead::new(channels as u8, rate as u32).unwrap();
        let mut tags = OpusTags::new();
        tags.push("ENCODER", "opus-pure fuzz seed").unwrap();
        let mut w = OggOpusWriter::with_tags(Vec::new(), head, tags).unwrap();
        for pkt in &packets {
            w.write_packet(pkt).unwrap();
        }
        written += write_seed(&root, "ogg_read", &format!("{i}"), &w.finish().unwrap());

        // `caf_read` takes a whole container too. Stated one frame short, so
        // the seed carries a remainder count as a real recording does.
        let head = OpusHead::new(channels as u8, rate as u32).unwrap();
        let mut w = CafOpusWriter::new(std::io::Cursor::new(Vec::new()), head).unwrap();
        for (j, pkt) in packets.iter().enumerate() {
            if j + 1 == packets.len() {
                let short = (960 - 960 / 4) as u32;
                w.write_packet_with_duration(pkt, short).unwrap();
            } else {
                w.write_packet(pkt).unwrap();
            }
        }
        let caf = w.finish().unwrap().into_inner();
        written += write_seed(&root, "caf_read", &format!("{i}"), &caf);
    }

    println!("wrote {written} seeds under {}", root.display());
    assert!(written > 0, "no seeds were written");
}

fn write_seed(root: &std::path::Path, target: &str, name: &str, data: &[u8]) -> usize {
    let dir = root.join(target);
    std::fs::create_dir_all(&dir).expect("seed directory");
    std::fs::write(dir.join(format!("seed-{name}")), data).expect("seed file");
    1
}
